# -*- coding: utf-8 -*-
"""dsp coding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bcPiz_nZQHFkxDKcVCM4k3vwmIqZltm9
"""

import requests

def get_travel_time(api_key, origins, destinations):
    """
    Calculate travel times between multiple origins and destinations using Google Distance Matrix API.

    Parameters:
        api_key (str): Your Google Maps Distance Matrix API key.
        origins (list): List of origin addresses or latitude/longitude pairs.
        destinations (list): List of destination addresses or latitude/longitude pairs.

    Returns:
        dict: Travel times (in seconds) between each origin and destination pair.
    """
    base_url = "https://maps.googleapis.com/maps/api/distancematrix/json"

    # Convert lists of origins and destinations to pipe-separated strings
    origins_str = "|".join(origins)
    destinations_str = "|".join(destinations)

    # Parameters for the API request
    params = {
        "origins": origins_str,
        "destinations": destinations_str,
        "mode": "transit",  # 대중교통 바탕
        "key": api_key,
    }

    # Make the request
    response = requests.get(base_url, params=params)
    data = response.json()

    # Check for errors in the response
    if data.get("status") != "OK":
        print("Error in response:", data)
        return None

    # Parse travel times
    travel_times = {}
    for i, origin in enumerate(data["origin_addresses"]):
        travel_times[origin] = {}
        for j, destination in enumerate(data["destination_addresses"]):
            element = data["rows"][i]["elements"][j]
            if element["status"] == "OK":
                travel_time = element["duration"]["value"]  # Time in seconds
                travel_times[origin][destination] = travel_time
            else:
                travel_times[origin][destination] = None  # No route found

    return travel_times

import requests
import pandas as pd
import numpy as np
import folium
from folium.plugins import MiniMap

def elec_location(region,page_num):
    url = 'https://dapi.kakao.com/v2/local/search/keyword.json'
    params = {'query': region,'page': page_num}
    headers = {"Authorization": "KakaoAK 87b40cb5d8022b260431de3f207f259a"}  #api key:KakaoAK 87b40cb5d8022b260431de3f207f259a

    places = requests.get(url, params=params, headers=headers).json()['documents']
    total = requests.get(url, params=params, headers=headers).json()['meta']['total_count']

def elec_info(places):
    X = []
    Y = []
    stores = []
    road_address = []
    place_url = []
    ID = []
    for place in places:
        X.append(float(place['x']))
        Y.append(float(place['y']))
        stores.append(place['place_name'])
        road_address.append(place['road_address_name'])
        place_url.append(place['place_url'])
        ID.append(place['id'])

    ar = np.array([ID,stores, X, Y, road_address,place_url]).T
    df = pd.DataFrame(ar, columns = ['ID','stores', 'X', 'Y','road_address','place_url'])
    return df

def keywords(location_name):
    df = None
    for loca in location:
        for page in range(1,4):
            local_name = elec_location(loca, page)
            local_elec_info = elec_info(local_name)

            if df is None:
                df = local_elec_info
            elif local_elec_info is None:
                continue
            else:
                df = pd.concat([df, local_elec_info],join='outer', ignore_index = True)
    return df

import folium
from folium.plugins import MiniMap
import pandas as pd
import chardet

def make_combined_map(df1, df2, name1, name2):
    # 지도 생성하기 (기준 위치와 줌 레벨 설정)
    m = folium.Map(location=[37.715133, 127], zoom_start=12)
    # 미니맵 추가하기
    minimap = MiniMap()
    m.add_child(minimap)

    # 첫 번째 데이터프레임 (지하철 데이터) 마커 추가하기
    for i in range(len(df1)):
      folium.CircleMarker(
              [df1['위도'][i], df1['경도'][i]],
              radius=6.5,
              color='blue',
              fill=True,
              fill_color='blue',
              fill_opacity=0.6,
              tooltip=df1[name1][i]
      ).add_to(m)

    # 두 번째 데이터프레임 (버스정류장 데이터) 마커 추가하기
    for i in range(len(df2)):
        folium.CircleMarker(
            [df2['위도1'][i], df2['경도1'][i]],
            radius=5,
            color='red',
            fill=True,
            fill_color='yellow',
            fill_opacity=0.6,
            tooltip=df2[name2][i]  # '정류소명'을 버스 데이터의 컬럼명으로 가정
        ).add_to(m)

    return m

!pip install chardet

"""# **여기서부터 p-center 데이터 분석 시작**

# **p-center**
"""

!pip install pulp

import pandas as pd
import pulp

def solve_p_center(p, origin_df, destination_df):
    locations_origin = list(origin_df['location'].unique())  # origin 위치들
    locations_destination = list(destination_df['location'].unique())

    # 문제 정의
    prob = pulp.LpProblem('p_center', pulp.LpMinimize)

    # 변수
    x = pulp.LpVariable.dicts('x', (locations_origin, locations_destination), 0, 1, pulp.LpBinary)
    y = pulp.LpVariable.dicts('y', locations_destination, 0, 1, pulp.LpBinary)
    # x = pulp.LpVariable.dicts('x', (origin_locations, destination_locations), 0, 1, pulp.LpBinary)
    # y = pulp.LpVariable.dicts('y', destination_locations, 0, 1, pulp.LpBinary)
    M = pulp.LpVariable('M', lowBound=0, cat='Continuous')  # 최대 거리 변수

    # 목적 함수
    prob += M

    distance_dict = {(row['origin'], row['destination']): row['distance'] for _, row in distance_df.iterrows()}
    d = [(row['origini'], row['destinationi']) for _, row in distance_df.iterrows()]

    # 제약 조건
    for origin in locations_origin:
        prob += pulp.lpSum(x[origin][destination] for destination in destination_df['location']) == 1
        # prob += pulp.lpSum(x[origin][destination] for destination in destination_locations) == 1
        for destination in locations_destination:

            # distance_row = df[(df['O_x'] == origin[0]) & (df['O_y'] == origin[1]) &
            #                   (df['D_x'] == destination[0]) & (df['D_y'] == destination[1])]

            prob += x[origin][destination] * distance_df['distance'].values[0] <= M
            prob += x[origin][destination] <= y[destination]  # y값에 따라 x값 제한

    # 중앙 위치의 총 개수는 p개여야 합니다.
    prob += pulp.lpSum(y[location] for location in destination_df['location']) == p

    # 문제 풀기
    prob.solve()

    # 선택된 위치 반환
    centers = [location for location in locations_destination if y[location].value() == 1]
    return centers

# 예: 3개의 중앙 위치를 찾기 위해 함수 호출
# centers = solve_p_center(3, origin_df, destination_df)
# print(centers)

"""# 광진구"""

dis = []

"""**교통수단 분석**"""

## 맨 처음 csv 파일 넣어주기
## csv 파일에 origin, destination 둘 다 들어가있어야 됨.
## 광진구 파일만.
import pandas as pd

df = pd.read_csv('버정지하철광진구.csv', encoding='cp949')
d_df = pd.read_csv('동서대운광진나지.csv')
d_df = d_df[d_df['구']=='광진구']

origin_df = pd.DataFrame(df[['origin','위도','경도']])
destination_df = pd.DataFrame(d_df[['destination','위도1','경도1']])

origin_df['location'] = list(zip(origin_df['위도'], origin_df['경도']))
destination_df['location'] = list(zip(destination_df['위도1'], destination_df['경도1']))
destination_df = destination_df[~destination_df['location'].apply(lambda x: pd.isnull(x[0]) or pd.isnull(x[1]))]

from itertools import product
from geopy.distance import geodesic

origin_coords = origin_df[['origin','위도','경도']].drop_duplicates()
destination_coords = destination_df[['destination','위도1','경도1']].drop_duplicates()
destination_coords = destination_coords.dropna(subset = ['위도1', '경도1'])

pairs = list(product(
    origin_coords.itertuples(index=False),
    destination_coords.itertuples(index=False)
))

distances = []
for origin, destination in pairs:
    origin_point = (origin.위도, origin.경도)
    destination_point = (destination.위도1, destination.경도1)
    distance = geodesic(origin_point, destination_point).kilometers
    distances.append({
        'origin': origin.origin, #이름
        'destination':destination.destination,  #이름
        'origini': origin_point, #좌표
        'destinationi': destination_point, #좌표
        'distance': distance
    })

distance_df = pd.DataFrame(distances)
print(distance_df)

## 3개의 중앙 위치를 찾기 위해 함수 호출
centers = solve_p_center(12, origin_df, destination_df)
print("선택된 센터 위치:", centers)
m = []
for center in centers:
  (a, b) = center
  destination = destination_df.loc[destination_df['location'] == (a, b), 'destination'].iloc[0]
  m.append([destination, a, b]) #뒤에서 다시 destination으로 활용.
df2 = pd.DataFrame(m, columns = ['destination','위도1','경도1'])
print(df2)

import chardet

csv_file_path = '버정지하철광진구.csv'

with open(csv_file_path, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))
df1 = pd.read_csv(csv_file_path, encoding=result['encoding'])

# Create the map
combined_map = make_combined_map(df1, df2, 'origin', 'destination')
combined_map.save('combined_map_with_markers.html')
combined_map

"""**병원 분석**"""

## 맨 처음 csv 파일 넣어주기
## csv 파일에 origin, destination 둘 다 들어가있어야 됨.
## 광진구 파일만.
import pandas as pd

df = pd.read_csv('병원광진구.csv', encoding='cp949')

print(df)
origin_df = pd.DataFrame(df[['origin','위도','경도']])
destination_df = pd.DataFrame(df2[['destination','위도1','경도1']])

origin_df['location'] = list(zip(origin_df['위도'], origin_df['경도']))
destination_df['location'] = list(zip(destination_df['위도1'], destination_df['경도1']))
destination_df = destination_df[~destination_df['location'].apply(lambda x: pd.isnull(x[0]) or pd.isnull(x[1]))]

from itertools import product
from geopy.distance import geodesic

origin_coords = origin_df[['origin','위도','경도']].drop_duplicates()
destination_coords = destination_df[['destination','위도1','경도1']].drop_duplicates()
destination_coords = destination_coords.dropna(subset = ['위도1', '경도1'])

print(origin_coords)

pairs = list(product(
    origin_coords.itertuples(index=False),
    destination_coords.itertuples(index=False)
))



distances = []

for origin, destination in pairs:
    origin_point = (origin.위도, origin.경도)
    destination_point = (destination.위도1, destination.경도1)
    distance = geodesic(origin_point, destination_point).kilometers
    distances.append({
        'origin': origin.origin, #이름
        'destination':destination.destination,  #이름
        'origini': origin_point, #좌표
        'destinationi': destination_point, #좌표
        'distance': distance
    })

distance_df = pd.DataFrame(distances)
print(distance_df)

# # 3개의 중앙 위치를 찾기 위해 함수 호출
centers = solve_p_center(6, origin_df, destination_df)
print("선택된 센터 위치:", centers)
m = []
for center in centers:
  (a, b) = center
  destination = destination_df.loc[destination_df['location'] == (a, b), 'destination'].iloc[0]
  m.append([destination, a, b]) #뒤에서 다시 destination으로 활용.
df2 = pd.DataFrame(m, columns = ['destination','위도1','경도1'])
print(df2)

import chardet

csv_file_path = '병원광진구.csv'

with open(csv_file_path, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))
df1 = pd.read_csv(csv_file_path, encoding=result['encoding'])


# Create the map
combined_map = make_combined_map(df1, df2, 'origin', 'destination')
combined_map.save('combined_map_with_markers.html')
combined_map

"""**경찰서 분석**"""

## 맨 처음 csv 파일 넣어주기
## csv 파일에 origin, destination 둘 다 들어가있어야 됨.
## 광진구 파일만.
import pandas as pd

o_df = pd.read_csv('경찰서광진구.csv',  encoding='cp949')

origin_df = pd.DataFrame(o_df[['origin','위도','경도']])
destination_df = pd.DataFrame(df2[['destination','위도1','경도1']])

origin_df['location'] = list(zip(origin_df['위도'], origin_df['경도']))
destination_df['location'] = list(zip(destination_df['위도1'], destination_df['경도1']))
destination_df = destination_df[~destination_df['location'].apply(lambda x: pd.isnull(x[0]) or pd.isnull(x[1]))]
print(destination_df)

!pip install pulp

from itertools import product
from geopy.distance import geodesic

origin_coords = origin_df[['origin','위도','경도']].drop_duplicates()
destination_coords = destination_df[['destination','위도1','경도1']].drop_duplicates()
destination_coords = destination_coords.dropna(subset = ['위도1', '경도1'])

pairs = list(product(
    origin_coords.itertuples(index=False),
    destination_coords.itertuples(index=False)
))

distances = []
for origin, destination in pairs:
    origin_point = (origin.위도, origin.경도)
    destination_point = (destination.위도1, destination.경도1)
    distance = geodesic(origin_point, destination_point).kilometers
    distances.append({
        'origin': origin.origin, #이름
        'destination':destination.destination,  #이름
        'origini': origin_point, #좌표
        'destinationi': destination_point, #좌표
        'distance': distance
    })

distance_df = pd.DataFrame(distances)
print(distance_df)

# # 3개의 중앙 위치를 찾기 위해 함수 호출
centers = solve_p_center(1, origin_df, destination_df)
print("선택된 센터 위치:", centers)
m = []
for center in centers:
  (a, b) = center
  destination = destination_df.loc[destination_df['location'] == (a, b), 'destination'].iloc[0]
  m.append([destination, a, b]) #뒤에서 다시 destination으로 활용.
df2 = pd.DataFrame(m, columns = ['destination','위도1','경도1'])
print(df2)

print(dis)

import chardet

csv_file_path = '경찰서광진구.csv'

with open(csv_file_path, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))
df1 = pd.read_csv(csv_file_path, encoding=result['encoding'])

# Create the map
combined_map = make_combined_map(df1, df2, 'origin', 'destination')
combined_map.save('combined_map_with_markers.html')
combined_map

"""# 동대문구"""

dis1 = []

"""**교통수단 분석**"""

import pandas as pd

d_df = pd.read_csv('동서대운광진나지.csv')
d_df = d_df[d_df['구']=='동대문구']
o_df = pd.read_csv('버정지하철동대문.csv', encoding='cp949')

origin_df = pd.DataFrame(o_df[['origin','위도','경도']])
destination_df = pd.DataFrame(d_df[['destination','위도1','경도1']])

origin_df['location'] = list(zip(origin_df['위도'], origin_df['경도']))
destination_df['location'] = list(zip(destination_df['위도1'], destination_df['경도1']))
destination_df = destination_df[~destination_df['location'].apply(lambda x: pd.isnull(x[0]) or pd.isnull(x[1]))]
print(destination_df)

from itertools import product
from geopy.distance import geodesic

origin_coords = origin_df[['origin','위도','경도']].drop_duplicates()
destination_coords = destination_df[['destination','위도1','경도1']].drop_duplicates()
destination_coords = destination_coords.dropna(subset = ['위도1', '경도1'])

pairs = list(product(
    origin_coords.itertuples(index=False),
    destination_coords.itertuples(index=False)
))

distances = []
for origin, destination in pairs:
    origin_point = (origin.위도, origin.경도)
    destination_point = (destination.위도1, destination.경도1)
    distance = geodesic(origin_point, destination_point).kilometers
    distances.append({
        'origin': origin.origin, #이름
        'destination':destination.destination,  #이름
        'origini': origin_point, #좌표
        'destinationi': destination_point, #좌표
        'distance': distance
    })

distance_df = pd.DataFrame(distances)
print(distance_df)

centers = solve_p_center(11, origin_df, destination_df)
print("선택된 센터 위치:", centers)
m = []
for center in centers:
  (a, b) = center
  destination = destination_df.loc[destination_df['location'] == (a, b), 'destination'].iloc[0]
  m.append([destination, a, b]) #뒤에서 다시 destination으로 활용.
df2 = pd.DataFrame(m, columns = ['destination','위도1','경도1'])
print(df2)

import chardet

csv_file_path = '버정지하철동대문.csv'

with open(csv_file_path, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))
df1 = pd.read_csv(csv_file_path, encoding=result['encoding'])

# Create the map
combined_map = make_combined_map(df1, df2, 'origin', 'destination')
combined_map.save('combined_map_with_markers.html')
combined_map

"""# **nn**

**병원**
"""

import pandas as pd

o_df = pd.read_csv('병원동대문.csv', encoding='cp949')

origin_df = pd.DataFrame(o_df[['origin','위도','경도']])
destination_df = pd.DataFrame(df2[['destination','위도1','경도1']])

origin_df['location'] = list(zip(origin_df['위도'], origin_df['경도']))
destination_df['location'] = list(zip(destination_df['위도1'], destination_df['경도1']))
destination_df = destination_df[~destination_df['location'].apply(lambda x: pd.isnull(x[0]) or pd.isnull(x[1]))]
print(df2)

from itertools import product
from geopy.distance import geodesic

origin_coords = origin_df[['origin','위도','경도']].drop_duplicates()
destination_coords = destination_df[['destination','위도1','경도1']].drop_duplicates()
destination_coords = destination_coords.dropna(subset = ['위도1', '경도1'])

pairs = list(product(
    origin_coords.itertuples(index=False),
    destination_coords.itertuples(index=False)
))

distances = []
for origin, destination in pairs:
    origin_point = (origin.위도, origin.경도)
    destination_point = (destination.위도1, destination.경도1)
    distance = geodesic(origin_point, destination_point).kilometers
    distances.append({
        'origin': origin.origin, #이름
        'destination':destination.destination,  #이름
        'origini': origin_point, #좌표
        'destinationi': destination_point, #좌표
        'distance': distance
    })

distance_df = pd.DataFrame(distances)
print(distance_df)

centers = solve_p_center(6, origin_df, destination_df)
print("선택된 센터 위치:", centers)
m = []
for center in centers:
  (a, b) = center
  destination = destination_df.loc[destination_df['location'] == (a, b), 'destination'].iloc[0]
  m.append([destination, a, b]) #뒤에서 다시 destination으로 활용.
df2 = pd.DataFrame(m, columns = ['destination','위도1','경도1'])
print(df2)

import chardet

csv_file_path = '병원동대문.csv'

with open(csv_file_path, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))
df1 = pd.read_csv(csv_file_path, encoding=result['encoding'])

# Create the map
combined_map = make_combined_map(df1, df2, 'origin', 'destination')
combined_map.save('combined_map_with_markers.html')
combined_map

"""# **hh**

**경찰서**
"""

import pandas as pd


o_df = pd.read_csv('경찰서동대문.csv', encoding='cp949')

origin_df = pd.DataFrame(o_df[['origin','위도','경도']])
destination_df = pd.DataFrame(df2[['destination','위도1','경도1']])

origin_df['location'] = list(zip(origin_df['위도'], origin_df['경도']))
destination_df['location'] = list(zip(destination_df['위도1'], destination_df['경도1']))
destination_df = destination_df[~destination_df['location'].apply(lambda x: pd.isnull(x[0]) or pd.isnull(x[1]))]
print(destination_df)

from itertools import product
from geopy.distance import geodesic

origin_coords = origin_df[['origin','위도','경도']].drop_duplicates()
destination_coords = destination_df[['destination','위도1','경도1']].drop_duplicates()
destination_coords = destination_coords.dropna(subset = ['위도1', '경도1'])

pairs = list(product(
    origin_coords.itertuples(index=False),
    destination_coords.itertuples(index=False)
))

distances = []
for origin, destination in pairs:
    origin_point = (origin.위도, origin.경도)
    destination_point = (destination.위도1, destination.경도1)
    distance = geodesic(origin_point, destination_point).kilometers
    distances.append({
        'origin': origin.origin, #이름
        'destination':destination.destination,  #이름
        'origini': origin_point, #좌표
        'destinationi': destination_point, #좌표
        'distance': distance
    })

distance_df = pd.DataFrame(distances)
print(distance_df)

centers = solve_p_center(1, origin_df, destination_df)
print("선택된 센터 위치:", centers)
m = []
for center in centers:
  (a, b) = center
  destination = destination_df.loc[destination_df['location'] == (a, b), 'destination'].iloc[0]
  m.append([destination, a, b]) #뒤에서 다시 destination으로 활용.
df2 = pd.DataFrame(m, columns = ['destination','위도1','경도1'])
print(df2)

import chardet

csv_file_path = '경찰서동대문.csv'

with open(csv_file_path, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))
df1 = pd.read_csv(csv_file_path, encoding=result['encoding'])

# Create the map
combined_map = make_combined_map(df1, df2, 'origin', 'destination')
combined_map.save('combined_map_with_markers.html')
combined_map

"""# 서대문구

**교통수단 분석**
"""

import pandas as pd

d_df = pd.read_csv('동서대운광진나지.csv')
d_df = d_df[d_df['구']=='서대문구']
o_df = pd.read_csv('버정지하철서대문.csv',encoding='cp949')

origin_df = pd.DataFrame(o_df[['origin','위도','경도']])
destination_df = pd.DataFrame(d_df[['destination','위도1','경도1']])

origin_df['location'] = list(zip(origin_df['위도'], origin_df['경도']))
destination_df['location'] = list(zip(destination_df['위도1'], destination_df['경도1']))
destination_df = destination_df[~destination_df['location'].apply(lambda x: pd.isnull(x[0]) or pd.isnull(x[1]))]

from itertools import product
from geopy.distance import geodesic

origin_coords = origin_df[['origin','위도','경도']].drop_duplicates()
destination_coords = destination_df[['destination','위도1','경도1']].drop_duplicates()
destination_coords = destination_coords.dropna(subset = ['위도1', '경도1'])

pairs = list(product(
    origin_coords.itertuples(index=False),
    destination_coords.itertuples(index=False)
))

distances = []
for origin, destination in pairs:
    origin_point = (origin.위도, origin.경도)
    destination_point = (destination.위도1, destination.경도1)
    distance = geodesic(origin_point, destination_point).kilometers
    distances.append({
        'origin': origin.origin, #이름
        'destination':destination.destination,  #이름
        'origini': origin_point, #좌표
        'destinationi': destination_point, #좌표
        'distance': distance
    })

distance_df = pd.DataFrame(distances)
print(distance_df)

centers = solve_p_center(12, origin_df, destination_df)
print("선택된 미디안 위치:", centers)
m = []
for center in centers:
  (a, b) = center
  destination = destination_df.loc[destination_df['location'] == (a, b), 'destination'].iloc[0]
  m.append([destination, a, b]) #뒤에서 다시 destination으로 활용.
df2 = pd.DataFrame(m, columns = ['destination','위도1','경도1'])
print(df2)

import chardet

csv_file_path = '버정지하철서대문.csv'

with open(csv_file_path, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))
df1 = pd.read_csv(csv_file_path, encoding=result['encoding'])


# Create the map
combined_map = make_combined_map(df1, df2, 'origin', 'destination')
combined_map.save('combined_map_with_markers.html')
combined_map

"""# **sdds**

**병원**
"""

import pandas as pd

o_df = pd.read_csv('병원서대문.csv', encoding='cp949')

origin_df = pd.DataFrame(o_df[['origin','위도','경도']])
destination_df = pd.DataFrame(df2[['destination','위도1','경도1']])

origin_df['location'] = list(zip(origin_df['위도'], origin_df['경도']))
destination_df['location'] = list(zip(destination_df['위도1'], destination_df['경도1']))
destination_df = destination_df[~destination_df['location'].apply(lambda x: pd.isnull(x[0]) or pd.isnull(x[1]))]
print(destination_df)
print(origin_df)

from itertools import product
from geopy.distance import geodesic

origin_coords = origin_df[['origin','위도','경도']].drop_duplicates()
destination_coords = destination_df[['destination','위도1','경도1']].drop_duplicates()
destination_coords = destination_coords.dropna(subset = ['위도1', '경도1'])

pairs = list(product(
    origin_coords.itertuples(index=False),
    destination_coords.itertuples(index=False)
))

distances = []
for origin, destination in pairs:
    origin_point = (origin.위도, origin.경도)
    destination_point = (destination.위도1, destination.경도1)
    distance = geodesic(origin_point, destination_point).kilometers
    distances.append({
        'origin': origin.origin, #이름
        'destination':destination.destination,  #이름
        'origini': origin_point, #좌표
        'destinationi': destination_point, #좌표
        'distance': distance
    })

distance_df = pd.DataFrame(distances)
print(distance_df)

centers = solve_p_center(6, origin_df, destination_df)
print("선택된 센터 위치:", centers)
m = []
for center in centers:
  (a, b) = center
  destination = destination_df.loc[destination_df['location'] == (a, b), 'destination'].iloc[0]
  m.append([destination, a, b]) #뒤에서 다시 destination으로 활용.
df2 = pd.DataFrame(m, columns = ['destination','위도1','경도1'])
print(df2)

import chardet

csv_file_path = '병원서대문.csv'

with open(csv_file_path, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))
df1 = pd.read_csv(csv_file_path, encoding=result['encoding'])

# Create the map
combined_map = make_combined_map(df1, df2, 'origin', 'destination')
combined_map.save('combined_map_with_markers.html')
combined_map

"""# sdsd

**경찰서**
"""

import pandas as pd

o_df = pd.read_csv('경찰서서대문.csv', encoding='cp949')

origin_df = pd.DataFrame(o_df[['origin','위도','경도']])
destination_df = pd.DataFrame(df2[['destination','위도1','경도1']])

origin_df['location'] = list(zip(origin_df['위도'], origin_df['경도']))
destination_df['location'] = list(zip(destination_df['위도1'], destination_df['경도1']))
destination_df = destination_df[~destination_df['location'].apply(lambda x: pd.isnull(x[0]) or pd.isnull(x[1]))]
print(destination_df)

from itertools import product
from geopy.distance import geodesic

origin_coords = origin_df[['origin','위도','경도']].drop_duplicates()
destination_coords = destination_df[['destination','위도1','경도1']].drop_duplicates()
destination_coords = destination_coords.dropna(subset = ['위도1', '경도1'])

pairs = list(product(
    origin_coords.itertuples(index=False),
    destination_coords.itertuples(index=False)
))

distances = []
for origin, destination in pairs:
    origin_point = (origin.위도, origin.경도)
    destination_point = (destination.위도1, destination.경도1)
    distance = geodesic(origin_point, destination_point).kilometers
    distances.append({
        'origin': origin.origin, #이름
        'destination':destination.destination,  #이름
        'origini': origin_point, #좌표
        'destinationi': destination_point, #좌표
        'distance': distance
    })

distance_df = pd.DataFrame(distances)
print(distance_df)

centers = solve_p_center(1, origin_df, destination_df)
print("선택된 미디안 위치:", centers)
m = []
for center in centers:
  (a, b) = center
  destination = destination_df.loc[destination_df['location'] == (a, b), 'destination'].iloc[0]
  m.append([destination, a, b]) #뒤에서 다시 destination으로 활용.
df2 = pd.DataFrame(m, columns = ['destination','위도1','경도1'])
print(df2)

import chardet

csv_file_path = '경찰서서대문.csv'

with open(csv_file_path, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(10000))
df1 = pd.read_csv(csv_file_path, encoding=result['encoding'])


# Create the map
combined_map = make_combined_map(df1, df2, 'origin', 'destination')
combined_map.save('combined_map_with_markers.html')
combined_map